version: '3'

vars:
    GOFILES:
        sh: >-
            find ./go -type f -mindepth 1 -maxdepth 1 -regex ".*\.go$" \
                | grep -v "_test.go"  \
                | tr '\n' ' '
    CURDIR:
        sh: pwd

    DDPAPPDIR:
        sh: echo $(pwd  | grep -Po ".*(?=\/)")/ddp-app

tasks:
    default:
        cmds:
            - task: push

    push:
        desc: push views into rdmo
        sources:
            - go/*.go
            - go/**/*.go
            - content/**/*
        method: timestamp
        cmds:
            - cmd: GOPATH={{.CURDIR}} go run {{.GOFILES}}
            - cmd: ${HOME}/rolling/sh/shelltools/reload-browser
