version: '3'

vars:
    CURDIR:
        sh: pwd

    DDPAPPDIR:
        sh: echo $(pwd  | grep -Po ".*(?=\/)")/ddp-app

tasks:
    default:
        cmds:
            - task: push

    push:
        desc: push views into rdmo
        sources:
            - content/*
            - py/*
        method: timestamp
        cmds:
            - cmd: python3 py/main.py
            - cmd: ${HOME}/rolling/sh/shelltools/reload-browser
