version: '3'

vars:
    GOFILES:
        sh: >-
            find ./go -type f -mindepth 1 -maxdepth 1 -regex ".*\.go$" \
                | grep -v "_test.go"  \
                | tr '\n' ' '

tasks:
    default:
        cmds:
            - cmd: clear
            - cmd: go run {{.GOFILES}}
            - cmd: /home/ole/rolling/sh/shelltools/reload-browser
        sources:
            - "go/**/*.go"
            - "content/html/*.html"
            - "content/tpl/*.json"

    srv:
        cmds:
            - cmd: cd docker/content-server && sudo docker-compose up -d
