id = "<ID>"
uri  = "<URI>"
uri_prefix = "<URI_PREFIX>"
key = "ddp_dmp"
comment = "<COMMENT>"
available = true
catalogs = []
sites = [1]
groups = []
template = ""
title_en = ""
help_en = ""
title_de = ""
help_de = ""
title_fr = ""
help_fr = ""
title_it = ""
help_it = ""
